
export const I18N = {
    FR: {
        titleFallback: "Taskmaster",
        subtitleFallback: "Tâches récurrentes",

        btnParams: "Paramètres",
        btnLoginUser: "Connexion user",
        btnLoginAdmin: "Connexion admin",
        connected: "Connecté",
        logout: "Se déconnecter",

        from: "Du",
        to: "Au",
        status: "Statut",
        all: "Tous",
        pending: "En cours",
        validated: "Validé",
        failed: "Échec",
        missing: "Missing",
        search: "Recherche",
        searchPlaceholder: "Recherche",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        refresh: "Rafraîchir",
        none: "Aucune tâche affichable pour cette période.",
        adminCreate: "Admin - Créer une tâche",
        choosePeriodicity: "Périodicité",
        description: "Description",
        procLink: "Lien de procédure",
        startDate: "Date de début (Obligatoire)",
        endDateYearly: "Date de fin (Obligatoire)",
        create: "Créer",
        existingTasks: "Admin - Tâches existantes",
        stopFuture: "L'historique sera conservé mais arrêter les occurrences futures de cette tâche ?",
        delete: "Supprimer",
        guestReadOnly: "Mode invité (Lecture seule)",
        comment: "Commentaire :",
        ferieNote: "Jour férié (Tâche non requise)",
        validate: "Valider",
        fail: "Échec",
        missing: "Manqué",
        proc: "Procédure",
        adminPanel: "Panneau admin",
        choosePeriodicityPlaceholder: "Choisir la périodicité…",
        daily: "Quotidien",
        weekly: "Hebdomadaire",
        monthly: "Mensuel",
        yearly: "Annuel",
        stop: "Stop",
        edit: "Editer",
        hardDeleteWarning: "Suppression définitive : la tâche sera supprimée de la base, ainsi que tous les statuts/notifs associés. Cette action est irréversible.",

        // Holiday info
        holidayInfoTitle: "Jours fériés par pays",
        holidayInfoIntro: "Le pays sélectionné est utilisé pour tenir compte des jours fériés nationaux lors de la génération des tâches.",
        holidayInfoHint: "La liste exacte dépend de l’année et est gérée côté serveur à l’aide d’une bibliothèque de jours fériés.",

        // Modals login / setup / params
        loginUserTitle: "Connexion utilisateur",
        loginAdminTitle: "Connexion admin",
        pwdUser: "Mot de passe user",
        pwdAdmin: "Mot de passe admin",
        doLogin: "Se connecter",
        passwordPlaceholder: "Mot de passe",

        setupTitle: "Configuration initiale",
        setupAdminPwd: "Mot de passe admin",
        setupUserPwd: "Mot de passe user",
        appTitle: "Titre de l'application",
        appSubtitle: "Sous-titre de l'application",
        taskManagement: "Gestion des tâches",
        logo: "Logo",
        favicon: "Favicon",
        country: "Gestion des jours fériés",
        language: "Langue (UI)",
        theme: "Thème de couleur",
        displayMode: "Mode d'affichage",
        displayModeLight: "Clair",
        displayModeDark: "Sombre",
        displayModeSystem: "Système",

        // Auto export
        autoExportLegend: "Export automatique",
        autoExportEnableShort: "Activer",
        autoExportFreq: "Fréquence",
        autoExportFreqDaily: "Tous les jours",
        autoExportFreqWeekly: "Toutes les semaines",
        autoExportFreqMonthly: "Tous les mois",
        autoExportTestButton: "Tester l'export",
        cleanupRetentionLabel: "Durée de rétention",
        retentionNever: "Ne jamais supprimer",
        retention1Month: "1 mois",
        retention6Months: "6 mois",
        retention1Year: "1 an",
        retention10Years: "10 ans",
        exportDir: "Dossier d’export (Chemin)",
        offsetFrom: "Décalage Début (Jours avant)",
        offsetTo: "Décalage Fin (Jours avant)",
        preview: "Aperçu",
        previewIntro: "Avec les réglages actuels, l'export d'aujourd'hui couvrirait :",

        // Email
        emailNotifLegend: "Notification email",
        emailNotifHintShort: "Activer SMTP",
        smtpHost: "SMTP host",
        smtpPort: "SMTP port",
        smtpSecure: "TLS/SSL (Secure)",
        smtpUser: "SMTP user (Optionnel)",
        smtpPass: "SMTP pass (Optionnel)",
        mailFrom: "From: nom <mail@exemple>",
        mailTo: "To: destinataire(s)",
        emailMissingEnable: "Envoyer un email pour les éléments manquées",
        emailExportEnable: "Envoyer aussi les exports automatiques par email",
        emailExportLegend: "Export par Email",
        emailExportSub: "Recevoir une copie des fichiers exportés par email",
        emailTestButton: "Test SMTP",
        emailTestExportButton: "Test Export Email",
        emailExportNoFormat: "Veuillez sélectionner au moins un format (CSV ou PDF) pour l'export email.",
        emailExportFormats: "Formats d'export par email",
        exportFormats: "Formats d'export",
        exportFormatMissing: "Veuillez sélectionner au moins un format d'export (CSV ou PDF).",
        exportTime: "Heure d'exécution",
        exportDayOfWeek: "Jour de la semaine",
        exDayOfMonth: "Jour du mois",
        exLastDayOfMonth: "Dernier jour du mois",
        monthlyTypeSpecific: "Date spécifique",
        monthlyTypeRelative: "Jour relatif",
        rankFirst: "Premier",
        rankSecond: "Deuxième",
        rankThird: "Troisième",
        rankFourth: "Quatrième",
        rankLast: "Dernier",
        dayMon: "Lundi",
        dayTue: "Mardi",
        dayWed: "Mercredi",
        dayThu: "Jeudi",
        dayFri: "Vendredi",
        daySat: "Samedi",
        daySun: "Dimanche",
        setupSmtpBtn: "Configurer SMTP",
        setupSmtpModalTitle: "Configuration SMTP",
        loading: "Chargement...",
        testExportNow: "Export Local",
        testExportEmail: "Export Email",
        chooseFile: "Choisir un fichier",
        noFileChosen: "Aucun fichier sélectionné",
        security: "Sécurité",
        adminPwd: "Mot de passe Admin",
        userPwd: "Mot de passe Utilisateur",
        pwdPlaceholder: "Laisser vide pour ne pas changer",
        changePwd: "Changer le mot de passe",
        newPwd: "Nouveau mot de passe",
        confirmPwd: "Confirmer le mot de passe",
        pwdStrength: "Force : ",
        weak: "Faible",
        strong: "Fort",
        pwdMismatch: "Les mots de passe ne correspondent pas",
        pwdChanged: "Modifié",
        cancel: "Annuler",
        confirm: "Confirmer",

        setupSubmit: "Valider le setup",
        setupHint: "Les mots de passe Admin et User sont requis pour finaliser la configuration. Tous les autres paramètres peuvent être modifiés ultérieurement dans les Paramètres de l'application.",
        paramsTitle: "Paramètres",
        paramsSave: "Enregistrer",

        // Edit task
        editTaskTitle: "Éditer la tâche",
        activeUntilLabel: "Actif jusqu'au (Optionnel)",

        // Delete confirm
        deleteConfirmTitle: "Confirmer la suppression",
        deleteConfirmYes: "Supprimer",
        deleteConfirmNo: "Annuler",
        deleteConfirmYes: "Supprimer",
        deleteConfirmNo: "Annuler",

        // Validate/Fail actions
        validateConfirmTitle: "Valider la tâche",
        validateMessage: "Confirmez-vous la validation de cette tâche ?",
        failConfirmTitle: "Signaler un échec",
        failMessage: "Veuillez indiquer la raison de l'échec ou un commentaire optionnel.",
        failCommentLabel: "Commentaire (Optionnel)",
        textPlaceholder: "Texte",
        exportLabel: "Export",
    },

    EN: {
        titleFallback: "Taskmaster",
        subtitleFallback: "Recurring tasks",

        btnParams: "Settings",
        btnLoginUser: "User sign-in",
        btnLoginAdmin: "Admin sign-in",
        connected: "Signed in",
        logout: "Sign out",

        from: "From",
        to: "To",
        status: "Status",
        all: "All",
        pending: "Pending",
        validated: "Validated",
        failed: "Failed",
        missing: "Missing",
        search: "Search",
        searchPlaceholder: "Search",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        refresh: "Refresh",
        none: "No tasks for this period / filters.",
        adminCreate: "Admin - Create a task",
        choosePeriodicity: "Periodicity",
        description: "Description",
        procLink: "Procedure link",
        startDate: "Start date (Required)",
        endDateYearly: "End date (Required)",
        create: "Create",
        existingTasks: "Admin - Existing tasks",
        stopFuture: "History will be kept but Stop future occurrences?",
        delete: "Delete",
        guestReadOnly: "Guest mode (Read only)",
        comment: "Comment:",
        ferieNote: "Public holiday (not Required)",
        validate: "Validate",
        fail: "Fail",
        proc: "Procedure",
        adminPanel: "Admin panel",
        choosePeriodicityPlaceholder: "Choose periodicity…",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
        stop: "Stop",
        edit: "Edit",
        hardDeleteWarning: "Permanent deletion: the task will be removed from the database along with all related statuses/notifications. This action cannot be undone.",

        // Holiday info
        holidayInfoTitle: "Public holidays by country",
        holidayInfoIntro: "The selected country is used to take national public holidays into account when generating tasks.",
        holidayInfoHint: "The exact list of holidays depends on the year and is handled server-side using a holiday library.",

        // Modals login / setup / params
        loginUserTitle: "User sign-in",
        loginAdminTitle: "Admin sign-in",
        pwdUser: "User password",
        pwdAdmin: "Admin password",
        doLogin: "Sign in",
        passwordPlaceholder: "Password",

        setupTitle: "Initial configuration",
        setupAdminPwd: "Admin password",
        setupUserPwd: "User password",
        appTitle: "Title of application",
        appSubtitle: "Application Subtitle",
        taskManagement: "Task Management",
        logo: "Logo",
        favicon: "Favicon",
        country: "Public Holidays Management (Country)",
        language: "Language (UI)",
        theme: "Color Theme",
        displayMode: "Display Mode",
        displayModeLight: "Light",
        displayModeDark: "Dark",
        displayModeSystem: "System",

        // Auto export
        autoExportLegend: "Auto export",
        autoExportEnableShort: "Enable",
        autoExportFreq: "Frequency",
        autoExportFreqDaily: "Every day",
        autoExportFreqWeekly: "Every week",
        autoExportFreqMonthly: "Every month",
        autoExportTestButton: "Test Export",
        cleanupRetentionLabel: "Retention period",
        retentionNever: "Never delete",
        retention1Month: "1 month",
        retention6Months: "6 months",
        retention1Year: "1 year",
        retention10Years: "10 years",
        exportDir: "Export directory (Path on server)",
        offsetFrom: "Offset From (Days ago)",
        offsetTo: "Offset To (Days ago)",
        preview: "Preview",
        previewIntro: "With current settings, today's export would cover:",

        // Email
        emailNotifLegend: "Email notification",
        emailNotifHintShort: "Enable SMTP",
        smtpHost: "SMTP host",
        smtpPort: "SMTP port",
        smtpSecure: "TLS/SSL (Secure)",
        smtpUser: "SMTP user (Optional)",
        smtpPass: "SMTP pass (Optional)",
        mailFrom: "From: name <mail@example>",
        mailTo: "To: recipient(s)",
        emailMissingEnable: "Send email for missing items",
        emailExportEnable: "Also send automatic exports by email",
        emailExportLegend: "Email Export",
        emailExportSub: "Receive a copy of exported files by email",
        emailTestButton: "Test SMTP",
        emailTestExportButton: "Test Export Email",
        emailExportNoFormat: "Please select at least one format (CSV or PDF) for email export.",
        emailExportFormats: "Email export formats",
        exportFormats: "Export formats",
        exportFormatMissing: "Please select at least one export format (CSV or PDF).",
        exportTime: "Execution time",
        exportDayOfWeek: "Day of the week",
        exDayOfMonth: "Day of the month",
        exLastDayOfMonth: "Last day of the month",
        monthlyTypeSpecific: "Specific date",
        monthlyTypeRelative: "Relative day",
        rankFirst: "First",
        rankSecond: "Second",
        rankThird: "Third",
        rankFourth: "Fourth",
        rankLast: "Last",
        dayMon: "Monday",
        dayTue: "Tuesday",
        dayWed: "Wednesday",
        dayThu: "Thursday",
        dayFri: "Friday",
        daySat: "Saturday",
        daySun: "Sunday",
        setupSmtpBtn: "Setup SMTP",
        setupSmtpModalTitle: "SMTP Configuration",
        loading: "Loading...",
        testExportNow: "Export Local",
        testExportEmail: "Export Email",
        chooseFile: "Choose File",
        noFileChosen: "No file chosen",
        security: "Security",
        adminPwd: "Admin Password",
        userPwd: "User Password",
        pwdPlaceholder: "Leave empty to keep unchanged",
        changePwd: "Change Password",
        newPwd: "New Password",
        confirmPwd: "Confirm Password",
        pwdStrength: "Strength: ",
        weak: "Weak",
        strong: "Strong",
        pwdMismatch: "Passwords do not match",
        pwdChanged: "Modified",
        cancel: "Cancel",
        confirm: "Confirm",

        setupSubmit: "Confirm setup",
        setupHint: "Admin and User passwords are Required to complete the setup. All other settings can be modified later in the application Settings.",
        paramsTitle: "Settings",
        paramsSave: "Save",

        // Edit task
        editTaskTitle: "Edit task",
        activeUntilLabel: "Active until (Optional)",

        // Delete confirm
        deleteConfirmTitle: "Confirm deletion",
        deleteConfirmYes: "Delete",
        deleteConfirmNo: "Cancel",
        deleteConfirmYes: "Delete",
        deleteConfirmNo: "Cancel",

        // Validate/Fail actions
        validateConfirmTitle: "Validate task",
        validateMessage: "Are you sure you want to validate this task?",
        failConfirmTitle: "Report failure",
        failMessage: "Please provide a reason or an optional comment.",
        failCommentLabel: "Comment (Optional)",
        textPlaceholder: "Text",
        exportLabel: "Export",
    }
};

export const COUNTRY_TIMEZONE = {
    FR: "Europe/Paris",
    US: "America/New_York",
    ES: "Europe/Madrid",
    UK: "Europe/London",
    DE: "Europe/Berlin",
    RO: "Europe/Bucharest",
    TN: "Africa/Tunis",
    CH: "Europe/Zurich",
    TR: "Europe/Istanbul"
};

export const COUNTRY_NAMES = {
    FR: "France",
    US: "United States",
    ES: "Spain",
    UK: "United Kingdom",
    DE: "Germany",
    RO: "Romania",
    TN: "Tunisia",
    CH: "Switzerland",
    TR: "Turkey"
};

export const PERIOD_COLORS = {
    daily: "bg-blue-100 text-blue-800 dark:bg-blue-500 dark:text-white",
    weekly: "bg-purple-100 text-purple-800 dark:bg-purple-500 dark:text-white",
    monthly: "bg-amber-100 text-amber-800 dark:bg-amber-500 dark:text-white",
    yearly: "bg-rose-100 text-rose-800 dark:bg-rose-500 dark:text-white",
};

export function t(lang, key) {
    const L = I18N[lang] || I18N.EN;
    return L[key] ?? I18N.EN[key] ?? key;
}
