
export const I18N = {
    FR: {
        titleFallback: "Taskmaster",
        subtitleFallback: "Tâches récurrentes",

        btnParams: "Paramètres",
        settingsGeneral: "Général",
        settingsEmail: "Email",
        settingsExport: "Export / Backup",
        connected: "Connecté",
        logout: "Se déconnecter",

        from: "Du",
        to: "Au",
        status: "Statut",
        all: "Tous",
        pending: "En cours",
        validated: "Validé",
        failed: "Échec",
        missing: "Manqué",
        search: "Recherche",
        searchPlaceholder: "Recherche",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        exportTitle: "Options d'exportation",
        exportDescription: "Sélectionnez les filtres pour générer votre fichier.",
        manageFilters: "Gérer mes filtres",
        saveAsPreset: "Enregistrer ce filtre",
        presetNamePlaceholder: "Nom du filtre (ex: Filtre RH)",
        applyPreset: "Appliquer un filtre enregistré",
        delegatedOnly: "Tâches déléguées uniquement",
        delegated: "Déléguées",
        searchResult: "Recherche dans les résultats",
        save: "Enregistrer",
        refresh: "Rafraîchir",
        none: "Aucune tâche affichable pour cette période.",
        adminCreate: "Admin - Créer une tâche",
        choosePeriodicity: "Périodicité",
        description: "Description",
        schedule: "Horaire",
        procLink: "Lien de procédure",
        startDate: "Date de début (Obligatoire)",
        endDateYearly: "Date de fin (Obligatoire)",
        create: "Créer",
        existingTasks: "Admin - Tâches existantes",
        stopFuture: "L'historique sera conservé mais arrêter les occurrences futures de cette tâche ?",
        delete: "Supprimer",
        guestReadOnly: "Mode invité (Lecture seule)",
        comment: "Commentaire :",
        ferieNote: "Jour férié (Tâche non requise)",
        validate: "Valider",
        fail: "Échec",
        proc: "Procédure",
        validatedBy: "Validé par :",
        failedBy: "Échoué par :",
        adminPanel: "Panneau admin",
        myTasksOnly: "Mes tâches uniquement",
        allTasks: "Toutes les tâches",
        tasks: "Tâches",
        solo: "Moi",
        choosePeriodicityPlaceholder: "Choisir la périodicité…",
        daily: "Quotidien",
        weekly: "Hebdomadaire",
        monthly: "Mensuel",
        yearly: "Annuel",
        stop: "Stop",
        edit: "Editer",
        hardDeleteWarning: "Suppression définitive : la tâche sera supprimée de la base, ainsi que tous les statuts/notifs associés. Cette action est irréversible.",

        // Holiday info
        holidayInfoTitle: "Jours fériés par pays",
        holidayInfoIntro: "Le pays sélectionné est utilisé pour tenir compte des jours fériés nationaux lors de la génération des tâches.",
        holidayInfoHint: "La liste exacte dépend de l’année et est gérée côté serveur à l’aide d’une bibliothèque de jours fériés.",

        // Modals login / setup / params
        loginUserTitle: "Connexion utilisateur",
        loginAdminTitle: "Connexion admin",
        doLogin: "Se connecter",
        passwordPlaceholder: "Mot de passe",

        setupTitle: "Configuration initiale",
        appTitle: "Titre de l'application",
        appSubtitle: "Sous-titre de l'application",
        taskManagement: "Gestion des tâches",
        logo: "Logo",
        favicon: "Favicon",
        country: "Gestion des jours fériés",
        language: "Langue (UI)",
        theme: "Thème de couleur",
        displayMode: "Mode d'affichage",
        displayModeLight: "Clair",
        displayModeDark: "Sombre",
        displayModeSystem: "Système",

        // Auto export
        autoExportLegend: "Export automatique",
        autoExportEnableShort: "Activer",
        autoExportFreq: "Fréquence",
        autoExportFreqDaily: "Tous les jours",
        autoExportFreqWeekly: "Toutes les semaines",
        autoExportFreqMonthly: "Tous les mois",
        autoExportTestButton: "Tester l'export",
        cleanupRetentionLabel: "Durée de rétention",
        retentionNever: "Ne jamais supprimer",
        retention1Month: "1 mois",
        retention6Months: "6 mois",
        retention1Year: "1 an",
        retention10Years: "10 ans",
        exportDir: "Dossier d’export (Chemin)",
        offsetFrom: "Décalage Début (Jours avant)",
        offsetTo: "Décalage Fin (Jours avant)",
        preview: "Aperçu",
        previewIntro: "Avec les réglages actuels, l'export d'aujourd'hui couvrirait :",

        // Email
        emailNotifLegend: "Notification email",
        emailNotifHintShort: "Activer SMTP",
        smtpConfiguration: "Configuration SMTP",
        smtpHost: "SMTP host",
        smtpPort: "SMTP port",
        smtpSecure: "TLS/SSL (Secure)",
        smtpUser: "SMTP user (Optionnel)",
        smtpPass: "SMTP pass (Optionnel)",
        mailFrom: "From: nom <mail@exemple>",
        mailTo: "To: destinataire(s)",
        fallback: "Secours",
        recipients: "Destinataires",
        admin: "Administrateurs",
        assignedUsers: "Utilisateurs assignés",
        custom: "Personnalisé",
        customEmails: "Emails personnalisés",
        separateEmailsComma: "Séparez les emails par des virgules",
        checkedEvery15Minutes: "Vérifié toutes les 15 minutes",
        checkedEvery10Minutes: "Vérifié toutes les 10 minutes",
        emailMissingEnable: "Envoyer un email pour les tâches manquées",
        emailReminderEnable: "Envoyer un rappel avant la fin de la tâche",
        emailExportEnable: "Envoyer aussi les exports automatiques par email",
        offsetHours: "Heures avant",
        offsetMinutes: "Minutes avant",
        emailExportLegend: "Export par Email",
        emailExportSub: "Recevoir une copie des fichiers exportés par email",
        emailTestButton: "Test SMTP",
        testSmtp: "Tester SMTP",
        emailTestExportButton: "Test Export Email",
        emailExportNoFormat: "Veuillez sélectionner au moins un format (CSV ou PDF) pour l'export email.",
        emailExportFormats: "Formats d'export par email",
        exportFormats: "Formats d'export",
        exportFormatMissing: "Veuillez sélectionner au moins un format d'export (CSV ou PDF).",
        exportTime: "Heure d'exécution",
        exportDayOfWeek: "Jour de la semaine",
        exDayOfMonth: "Jour du mois",
        exLastDayOfMonth: "Dernier jour du mois",
        monthlyTypeSpecific: "Date spécifique",
        monthlyTypeRelative: "Jour relatif",
        rankFirst: "Premier",
        rankSecond: "Deuxième",
        rankThird: "Troisième",
        rankFourth: "Quatrième",
        rankLast: "Dernier",
        dayMon: "Lundi",
        dayTue: "Mardi",
        dayWed: "Mercredi",
        dayThu: "Jeudi",
        dayFri: "Vendredi",
        daySat: "Samedi",
        daySun: "Dimanche",
        setupSmtpBtn: "Configurer SMTP",
        setupSmtpModalTitle: "Configuration SMTP",
        loading: "Chargement...",
        testExportNow: "Export Local",
        testExportEmail: "Export Email",
        chooseFile: "Choisir un fichier",
        noFileChosen: "Aucun fichier sélectionné",
        scheduleDetails: "Détails Horaire",
        taskStart: "Début",
        taskEnd: "Fin",
        weekendsIncluded: "Week-ends inclus",
        weekendsExcluded: "Week-ends exclus",
        holidaysIncluded: "Jours fériés inclus",
        holidaysExcluded: "Jours fériés exclus",
        recurrence: "Répétition",
        exceptions: "Exceptions",
        everyDay: "Tous les jours",
        everyWeek: "Toutes les semaines",
        everyMonth: "Tous les mois",

        // Dashboard
        completionRate: "Taux de Réalisation",
        pendingTasks: "Actions en Attente",
        missedTasks: "Manquées Aujourd'hui",
        onTime: "Ponctualité",
        weeklyActivity: "Activité Hebdomadaire",
        taskDistribution: "Types de Tâches",
        urgentPendingTasks: "Tâches Urgentes",
        urgentTasksDesc: "Liste des tâches se terminant bientôt",
        noRisks: "Aucun risque immédiat. Beau travail !",
        lastUpdated: "Dernière mise à jour",
        back: "Retour",
        dashboard: "Tableau de Bord",
        dashboardOverview: "Aperçu de la performance de l'équipe et de la santé des tâches.",
        weeklyActivityDesc: "Activité Hebdomadaire",
        tasksCompletedDesc: "tâches complétées",
        tasksWaitingDesc: "En attente de validation",
        tasksOverdueDesc: "En retard ou échouées",
        ofCompletedTasksDesc: "Sur les tâches complétées",
        trendHigh: "Haute Performance",
        trendAttention: "Nécessite Attention",
        trendStable: "Stable",

        // Security
        security: "Sécurité",
        pwdPlaceholder: "Laisser vide pour ne pas modifier",
        changePwd: "Changer le mot de passe",
        newPwd: "Nouveau mot de passe",
        confirmPwd: "Confirmer le mot de passe",
        pwdStrength: "Force : ",
        weak: "Faible",
        strong: "Fort",
        pwdMismatch: "Les mots de passe ne correspondent pas",
        pwdChanged: "Modifié",
        cancel: "Annuler",
        confirm: "Confirmer",

        // Setup specific
        setupSubmit: "Valider le setup",
        setupHint: "Le mot de passe Administrateur local est requis pour finaliser la configuration. Tous les autres paramètres peuvent être modifiés ultérieurement dans les Paramètres de l'application.",
        setupAdminPwd: "Mot de passe Administrateur",
        setupAdminPwdMsg: "Définissez le mot de passe administrateur pour sécuriser l'application.",
        adminPwdRequired: "Le mot de passe administrateur est requis",

        paramsTitle: "Paramètres",
        paramsSave: "Enregistrer",

        // Edit task
        editTaskTitle: "Éditer la tâche",
        activeUntilLabel: "Actif jusqu'au (Optionnel)",

        // Delete confirm
        deleteConfirmTitle: "Confirmer la suppression",
        deleteConfirmYes: "Supprimer",
        deleteConfirmNo: "Annuler",

        // Validate/Fail actions
        validateConfirmTitle: "Valider la tâche",
        validateMessage: "Confirmez-vous la validation de cette tâche ?",
        failConfirmTitle: "Signaler un échec",
        failMessage: "Veuillez indiquer la raison de l'échec ou un commentaire optionnel.",
        failCommentLabel: "Commentaire (Optionnel)",
        textPlaceholder: "Texte",
        exportLabel: "Export",

        // Features 2.0
        teamMembers: "Membres de l'équipe",
        addUser: "Ajouter un utilisateur",
        assignTo: "Attribuer à",
        assignedTo: "Attribué",
        unassigned: "Tout le monde",
        source: "Source",
        username: "Nom d'utilisateur",
        role: "Rôle",
        login: "Connexion",
        loginTitle: "S'identifier",
        minAdmin: "Définissez au moins un administrateur avec un mot de passe.",
        setPassword: "Définir le mot de passe...",
        changePassword: "Changer le mot de passe...",
        passwordFor: "Mot de passe pour",
        reassignTitle: "Réassigner les tâches",
        reassignIntro: "L'utilisateur a des tâches futures assignées. Vous devez les réassigner avant de supprimer ce compte.",
        reassignToUser: "Réassigner à un utilisateur",
        reassignToGroup: "Réassigner à un groupe",
        reassignConfirm: "Réassigner & Supprimer",
        fullName: "Prénom / Nom",
        emailAddr: "Email",
        editUserDetails: "Editer détail",
        invalidEmail: "Format d'email invalide",
        everyone: "Tout le monde",
        confirmDelegationEdit: "Modifier la délégation pour ce jour spécifique ?",
        noGroupAvailable: "Aucun groupe disponible",
        addGroup: "Ajouter un groupe",
        typeGroupname: "Nom du groupe",
        groupName: "Nom",
        groupNamePlaceholder: "Ex: Équipe A",
        groupAddSuccess: "Groupe ajouté avec succès",
        groupDeleteSuccess: "Groupe supprimé avec succès",
        groupConfirmDelete: "Supprimer ce groupe ?",
        selectAssignmentType: "Type d'assignation",
        group: "Groupe",
        user: "Utilisateur",
        selectGroup: "Sélectionner un groupe",
        usersSelected: "utilisateur(s) sélectionné(s)",
        groupManagement: "Gestion des groupes",
        customGroups: "Groupes personnalisés",
        noCustomGroups: "Aucun groupe personnalisé créé",
        deleteGroup: "Supprimer le groupe",
        deleteGroupConfirmation: "Êtes-vous sûr de vouloir supprimer le groupe",
        deleteGroupWarning: "Cette action est irréversible. Les utilisateurs assignés à ce groupe perdront cette affectation.",
        manageGroups: "Gérer les groupes",
        close: "Fermer",
        cannotDeleteGroup: "Impossible de supprimer le groupe",
        groupInUseError: "Le groupe ne peut pas être supprimé car il est actuellement assigné à",
        removeGroupFromUsers: "Veuillez retirer ce groupe de tous les utilisateurs avant de le supprimer.",

        // Delegation
        delegation: "Délégation",
        delegationActive: "Active",
        delegationTitle: "Délégation de tâche",
        delegateTo: "Déléguer à",
        selectUser: "Sélectionner un utilisateur...",
        startDateSimple: "Date de début",
        endDate: "Date de fin",
        endDateSimple: "Date de fin",
        addDelegation: "Ajouter",
        activeDelegations: "Délégations actives",
        noDelegations: "Aucune délégation",
        delegationAdded: "Délégation ajoutée",

        // Auth Config
        authTab: "Authentification",
        authAzureTitle: "Azure Active Directory (SSO)",
        authAzureEnable: "Activer l'authentification Azure AD",
        authAzureTenant: "Tenant ID (Annuaire)",
        authAzureClientId: "Client ID (Application)",
        authAzureClientSecret: "Client Secret",
        authLdapTitle: "LDAP / Active Directory",
        authLdapEnable: "Activer l'authentification LDAP",
        authLdapUrl: "URL Serveur (ldap://...)",
        authLdapBindDn: "Bind DN (Utilisateur de service)",
        authLdapBindPassword: "Mot de passe du Bind",
        authLdapSearchBase: "Base de recherche (DC=...)",
        authLdapFilter: "Filtre (ex: (sAMAccountName={{username}}))",
        confirmDeleteTitle: "Supprimer l'utilisateur",
        confirmDeleteUserDesc: "Voulez-vous vraiment supprimer cet utilisateur ? Cette action est irréversible.",
        deleteUser: "Supprimer",
        passwordChangeRequired: "Changement de mot de passe requis",
        changePasswordRequired: "Changement de mot de passe requis (Admin)",
        passwordChangeFailed: "Échec du changement de mot de passe",
        error: "Erreur",
        failedAddDelegation: "Échec de l'ajout de la délégation",
        failedRemoveDelegation: "Échec de la suppression de la délégation",
        skipWeekends: "Ignorer les weekends",
        skipHolidays: "Ignorer les jours fériés",
        hnoTitle: "Gestion HNO (Heures Non Ouvrées)",
        enableHNO: "Activer la fonctionnalité HNO",
        hnoGroups: "Groupes / Équipes HNO",
        addHNOGroup: "Ajouter un groupe HNO",
        hnoName: "Nom du groupe",
        hnoDays: "Jours de démarrage",
        hnoStart: "Heure de début",
        hnoEnd: "Heure de fin",
        hnoTaskType: "Tâche HNO",
        hno: "HNO",
        hnoGroupRequired: "Erreur: Le groupe HNO est obligatoire pour ce type de tâche.",
        selectHNOGroup: "Sélectionner le groupe HNO",
        manageHnoTeamsDesc: "Gérer les équipes et horaires pour les tâches HNO (Heures Non Ouvrées).",

        // Schedule Settings
        scheduleSettingsTitle: "Paramètres Horaires Standards",
        scheduleGlobalMode: "Utiliser un horaire global",
        scheduleGlobalDesc: "Appliquer les mêmes horaires à toutes les périodicités standards",
        scheduleParams: "Paramètres des horaires",
        schedDaily: "Horaire Quotidien",
        schedWeekly: "Horaire Hebdomadaire",
        schedMonthly: "Horaire Mensuel",
        schedYearly: "Horaire Annuel",

        success: "Succès",
        saved: "Enregistré",
        taskStopped: "Tâche arrêtée avec succès",
        taskDeleted: "Tâche supprimée avec succès",
        taskSaved: "Tâche enregistrée avec succès",

        assignedTo: "Attribué à",
        schedule: "Horaire",
        multipleGroups: "Plusieurs groupes",
        multipleUsers: "utilisateurs",

        // Backup
        backupTitle: "Sauvegarde & Restauration",
        backupDesc: "Créez une sauvegarde complète de votre configuration et de vos tâches, ou restaurez à partir d'une sauvegarde précédente.",
        backupDownload: "Télécharger la sauvegarde",
        backupRestore: "Restaurer une sauvegarde",
        backupRestoreConfirm: "Êtes-vous sûr ? Cela écrasera les données actuelles.",
        backupOptionsTitle: "Options de sauvegarde",
        backupIncludeFiles: "Inclure les fichiers locaux (procédures, logos, images)",
        exportBackupAction: "Exporter",
        backupJsonOnly: "Configuration seule (JSON)",
        backupFullZip: "Complète (Archive ZIP)",
        backupDownloading: "Téléchargement en cours...",
        backupRestoring: "Restauration en cours...",

        // Auto Backup
        autoBackupTitle: "Sauvegarde Automatique",
        autoBackupDesc: "Planifiez des sauvegardes automatiques de vos données.",
        autoBackupType: "Type de sauvegarde",
        autoBackupPassword: "Mot de passe de chiffrement (Optionnel)",
        autoBackupPasswordPlaceholder: "Laisser vide pour ne pas chiffrer",
        backupEncryptionWarning: "Attention : Si vous perdez ce mot de passe, les sauvegardes ne pourront pas être restaurées.",
        autoBackupLocation: "Emplacement des sauvegardes",
        backupRetentionCount: "Sauvegardes à conserver",
    },

    EN: {
        titleFallback: "Taskmaster",
        subtitleFallback: "Recurring tasks",

        btnParams: "Settings",
        settingsGeneral: "General",
        settingsEmail: "Email",
        settingsExport: "Export / Backup",
        connected: "Signed in",
        logout: "Sign out",

        from: "From",
        to: "To",
        status: "Status",
        all: "All",
        pending: "Pending",
        validated: "Validated",
        failed: "Failed",
        missing: "Missing",
        search: "Search",
        searchPlaceholder: "Search",
        exportCSV: "Export CSV",
        exportPDF: "Export PDF",
        exportTitle: "Export options",
        exportDescription: "Select filters to generate your file.",
        manageFilters: "Manage filters",
        saveAsPreset: "Save as preset",
        presetNamePlaceholder: "Preset name (e.g., HR)",
        applyPreset: "Apply a saved preset",
        delegatedOnly: "Delegated tasks only",
        delegated: "Delegated",
        searchResult: "Search in results",
        save: "Save",
        refresh: "Refresh",
        none: "No tasks for this period / filters.",
        adminCreate: "Admin - Create a task",
        choosePeriodicity: "Periodicity",
        description: "Description",
        schedule: "Schedule",
        procLink: "Procedure link",
        startDate: "Start date (Required)",
        endDateYearly: "End date (Required)",
        create: "Create",
        existingTasks: "Admin - Existing tasks",
        stopFuture: "History will be kept but Stop future occurrences?",
        delete: "Delete",
        guestReadOnly: "Guest mode (Read only)",
        comment: "Comment:",
        ferieNote: "Public holiday (not Required)",
        validate: "Validate",
        fail: "Fail",
        proc: "Procedure",
        validatedBy: "Validated by:",
        failedBy: "Failed by:",
        adminPanel: "Admin panel",
        myTasksOnly: "My tasks only",
        allTasks: "All tasks",
        tasks: "Tasks",
        solo: "Me",
        choosePeriodicityPlaceholder: "Choose periodicity…",
        daily: "Daily",
        weekly: "Weekly",
        monthly: "Monthly",
        yearly: "Yearly",
        stop: "Stop",
        edit: "Edit",
        hardDeleteWarning: "Permanent deletion: the task will be removed from the database along with all related statuses/notifications. This action cannot be undone.",

        // Holiday info
        holidayInfoTitle: "Public holidays by country",
        holidayInfoIntro: "The selected country is used to take national public holidays into account when generating tasks.",
        holidayInfoHint: "The exact list of holidays depends on the year and is handled server-side using a holiday library.",

        // Modals login / setup / params
        loginUserTitle: "User sign-in",
        loginAdminTitle: "Admin sign-in",
        doLogin: "Sign in",
        passwordPlaceholder: "Password",

        setupTitle: "Initial configuration",
        appTitle: "Title of application",
        appSubtitle: "Application Subtitle",
        taskManagement: "Task Management",
        logo: "Logo",
        favicon: "Favicon",
        country: "Public Holidays Management",
        language: "Language (UI)",
        theme: "Color Theme",
        displayMode: "Display Mode",
        displayModeLight: "Light",
        displayModeDark: "Dark",
        displayModeSystem: "System",

        // Auto export
        autoExportLegend: "Auto export",
        autoExportEnableShort: "Enable",
        autoExportFreq: "Frequency",
        autoExportFreqDaily: "Every day",
        autoExportFreqWeekly: "Every week",
        autoExportFreqMonthly: "Every month",
        autoExportTestButton: "Test Export",
        cleanupRetentionLabel: "Retention period",
        retentionNever: "Never delete",
        retention1Month: "1 month",
        retention6Months: "6 months",
        retention1Year: "1 year",
        retention10Years: "10 years",
        exportDir: "Export directory (Path on server)",
        offsetFrom: "Offset From (Days ago)",
        offsetTo: "Offset To (Days ago)",
        preview: "Preview",
        previewIntro: "With current settings, today's export would cover:",

        // Email
        emailNotifLegend: "Email notification",
        emailNotifHintShort: "Enable SMTP",
        smtpConfiguration: "SMTP Configuration",
        smtpHost: "SMTP host",
        smtpPort: "SMTP port",
        smtpSecure: "TLS/SSL (Secure)",
        smtpUser: "SMTP user (Optional)",
        smtpPass: "SMTP pass (Optional)",
        mailFrom: "From: name <mail@example>",
        mailTo: "To: recipient(s)",
        fallback: "Fallback",
        recipients: "Recipients",
        admin: "Administrators",
        assignedUsers: "Assigned Users",
        custom: "Custom",
        customEmails: "Custom Emails",
        separateEmailsComma: "Separate multiple emails with commas",
        checkedEvery15Minutes: "Checked every 15 minutes",
        checkedEvery10Minutes: "Checked every 10 minutes",
        emailMissingEnable: "Send email for missing tasks",
        emailReminderEnable: "Send reminder before task deadline",
        emailExportEnable: "Also send automatic exports by email",
        offsetHours: "Hours before",
        offsetMinutes: "Minutes before",
        emailExportLegend: "Email Export",
        emailExportSub: "Receive a copy of exported files by email",
        emailTestButton: "Test SMTP",
        testSmtp: "Test SMTP",
        emailTestExportButton: "Test Export Email",
        emailExportNoFormat: "Please select at least one format (CSV or PDF) for email export.",
        emailExportFormats: "Email export formats",
        scheduleDetails: "Schedule Details",
        taskStart: "Start",
        taskEnd: "End",
        weekendsIncluded: "Weekends included",
        weekendsExcluded: "Weekends excluded",
        holidaysIncluded: "Holidays included",
        holidaysExcluded: "Holidays excluded",
        recurrence: "Recurrence",
        exceptions: "Exceptions",
        everyDay: "Every day",
        everyWeek: "Every week",
        everyMonth: "Every month",
        exportFormats: "Export formats",
        exportFormatMissing: "Please select at least one export format (CSV or PDF).",
        exportTime: "Execution time",
        exportDayOfWeek: "Day of the week",
        exDayOfMonth: "Day of the month",
        exLastDayOfMonth: "Last day of the month",
        monthlyTypeSpecific: "Specific date",
        monthlyTypeRelative: "Relative day",
        rankFirst: "First",
        rankSecond: "Second",
        rankThird: "Third",
        rankFourth: "Fourth",
        rankLast: "Last",
        dayMon: "Monday",
        dayTue: "Tuesday",
        dayWed: "Wednesday",
        dayThu: "Thursday",
        dayFri: "Friday",
        daySat: "Saturday",
        daySun: "Sunday",
        setupSmtpBtn: "Setup SMTP",
        setupSmtpModalTitle: "SMTP Configuration",
        loading: "Loading...",
        testExportNow: "Export Local",
        testExportEmail: "Export Email",
        chooseFile: "Choose File",
        noFileChosen: "No file chosen",

        // Dashboard
        completionRate: "Completion Rate",
        pendingTasks: "Pending Actions",
        missedTasks: "Missed Today",
        onTime: "On-Time Ratio",
        weeklyActivity: "Weekly Activity",
        taskDistribution: "Task Types",
        urgentPendingTasks: "Urgent Pending Tasks",
        urgentTasksDesc: "Listing tasks ending soon",
        noRisks: "No immediate risks found. Good job!",
        lastUpdated: "Last updated",
        back: "Back",
        dashboard: "Dashboard",
        dashboardOverview: "Overview of team performance and task health.",
        weeklyActivityDesc: "Task Statuses",
        tasksCompletedDesc: "tasks completed",
        tasksWaitingDesc: "Tasks waiting for validation",
        tasksOverdueDesc: "Overdue or failed",
        missedTasks: "Missed / Failed",
        ofCompletedTasksDesc: "Of completed tasks",
        trendHigh: "High Performance",
        trendAttention: "Needs Attention",
        trendStable: "Stable",

        // Security
        security: "Security",
        pwdPlaceholder: "Leave empty to keep unchanged",
        changePwd: "Change Password",
        newPwd: "New Password",
        confirmPwd: "Confirm Password",
        pwdStrength: "Strength: ",
        weak: "Weak",
        strong: "Strong",
        pwdMismatch: "Passwords do not match",
        pwdChanged: "Modified",
        cancel: "Cancel",
        confirm: "Confirm",

        // Setup specific
        setupSubmit: "Confirm setup",
        setupHint: "Local Admin password is Required to complete the setup. All other settings can be modified later in the application Settings.",
        setupAdminPwd: "Administrator Password",
        setupAdminPwdMsg: "Define the administrator password to secure the application.",
        adminPwdRequired: "Administrator password is required",

        paramsTitle: "Settings",
        paramsSave: "Save",

        // Edit task
        editTaskTitle: "Edit task",
        activeUntilLabel: "Active until (Optional)",

        // Delete confirm
        deleteConfirmTitle: "Confirm deletion",
        deleteConfirmYes: "Delete",
        deleteConfirmNo: "Cancel",

        // Validate/Fail actions
        validateConfirmTitle: "Validate task",
        validateMessage: "Are you sure you want to validate this task?",
        failConfirmTitle: "Report failure",
        failMessage: "Please provide a reason or an optional comment.",
        failCommentLabel: "Comment (Optional)",
        textPlaceholder: "Text",
        exportLabel: "Export",

        // Features 2.0
        teamMembers: "Team Members",
        addUser: "Add User",
        assignTo: "Assign To",
        assignedTo: "Assigned To",
        unassigned: "Everyone",
        source: "Source",
        username: "Username",
        role: "Role",
        login: "Login",
        loginTitle: "Sign in",
        minAdmin: "Define at least one Admin. Passwords required.",
        setPassword: "Set Password...",
        changePassword: "Change Password...",
        passwordFor: "Password for",
        reassignTitle: "Reassign Tasks",
        reassignIntro: "User has future tasks assigned. You must reassign them before deleting this account.",
        reassignToUser: "Reassign to User",
        reassignToGroup: "Reassign to Group",
        reassignConfirm: "Reassign & Delete",
        fullName: "Full Name",
        emailAddr: "Email",
        editUserDetails: "Edit details",
        invalidEmail: "Invalid email format",
        everyone: "Everyone",
        confirmDelegationEdit: "Modify delegation for this specific day?",
        noGroupAvailable: "No group available",
        addGroup: "Add Group",
        typeGroupname: "Group Name",
        groupName: "Name",
        groupNamePlaceholder: "Ex: Team A",
        groupAddSuccess: "Group added successfully",
        groupDeleteSuccess: "Group deleted successfully",
        groupConfirmDelete: "Delete this group?",
        selectAssignmentType: "Assignment Type",
        group: "Group",
        user: "User",
        selectGroup: "Select Group",
        usersSelected: "user(s) selected",
        groupManagement: "Group Management",
        customGroups: "Custom Groups",
        noCustomGroups: "No custom groups created yet",
        deleteGroup: "Delete Group",
        deleteGroupConfirmation: "Are you sure you want to delete the group",
        deleteGroupWarning: "This action cannot be undone. Users assigned to this group will lose this assignment.",
        manageGroups: "Manage Groups",
        close: "Close",
        cannotDeleteGroup: "Cannot Delete Group",
        groupInUseError: "The group cannot be deleted because it is currently assigned to",
        removeGroupFromUsers: "Please remove this group from all users before deleting it.",

        // Delegation
        delegation: "Delegation",
        delegationActive: "Active",
        delegationTitle: "Task Delegation",
        delegateTo: "Delegate To",
        selectUser: "Select a user...",
        startDateSimple: "Start Date",
        endDate: "End Date",
        endDateSimple: "End Date",
        addDelegation: "Add",
        activeDelegations: "Active Delegations",
        noDelegations: "No active delegations",
        delegationAdded: "Delegation added",

        // Auth Config
        authTab: "Authentication",
        authAzureTitle: "Azure Active Directory (SSO)",
        authAzureEnable: "Enable Azure AD Authentication",
        authAzureTenant: "Tenant ID (Directory)",
        authAzureClientId: "Client ID (Application)",
        authAzureClientSecret: "Client Secret",
        authLdapTitle: "LDAP / Active Directory",
        authLdapEnable: "Enable LDAP Authentication",
        authLdapUrl: "Server URL (ldap://...)",
        authLdapBindDn: "Bind DN (Service User)",
        authLdapBindPassword: "Bind Password",
        authLdapSearchBase: "Search Base (DC=...)",
        authLdapFilter: "Filter (e.g. (sAMAccountName={{username}}))",
        confirmDeleteTitle: "Delete User",
        confirmDeleteUserDesc: "Are you sure you want to delete this user? This action cannot be undone.",
        deleteUser: "Delete User",
        passwordChangeRequired: "Password Change Required",
        changePasswordRequired: "Password Change Required (Admin)",
        passwordChangeFailed: "Password change failed",
        error: "Error",
        failedAddDelegation: "Failed to add delegation",
        failedRemoveDelegation: "Failed to remove delegation",
        skipWeekends: "Skip Weekends",
        skipHolidays: "Skip Holidays",
        hnoTitle: "HNO Management (After Hours)",
        enableHNO: "Enable HNO Feature",
        hnoGroups: "HNO Groups / Shifts",
        addHNOGroup: "Add HNO Group",
        hnoName: "Group Name",
        hnoDays: "Start Days",
        hnoStart: "Start Time",
        hnoEnd: "End Time",
        hnoTaskType: "HNO Task",
        hno: "HNO",
        hnoGroupRequired: "Validation error: HNO Group is required for this task type.",
        selectHNOGroup: "Select HNO Group",
        manageHnoTeamsDesc: "Manage teams and shifts for After Hours tasks.",

        // Schedule Settings
        scheduleSettingsTitle: "Standard Schedule Settings",
        scheduleGlobalMode: "Use Global Schedule",
        scheduleGlobalDesc: "Apply the same hours to all standard periodicities",
        scheduleParams: "Schedule Parameters",
        schedDaily: "Daily Schedule",
        schedWeekly: "Weekly Schedule",
        schedMonthly: "Monthly Schedule",
        schedYearly: "Yearly Schedule",

        success: "Success",
        saved: "Saved",
        taskStopped: "Task stopped successfully",
        taskDeleted: "Task deleted successfully",
        taskSaved: "Task saved successfully",

        assignedTo: "Assigned to",
        schedule: "Schedule",
        multipleGroups: "Multiple groups",
        multipleUsers: "users",

        // Backup
        backupTitle: "Backup & Restore",
        backupDesc: "Create a full backup of your configuration and tasks, or restore from a previous backup.",
        backupDownload: "Download Backup",
        backupRestore: "Restore Backup",
        backupRestoreConfirm: "Are you sure? This will overwrite current data.",
        backupOptionsTitle: "Backup Options",
        backupIncludeFiles: "Include local files (procedures, logos, images)",
        exportBackupAction: "Export",
        backupJsonOnly: "Configuration only (JSON)",
        backupFullZip: "Complete (ZIP Archive)",
        backupDownloading: "Downloading...",
        backupRestoring: "Restoring...",

        // Auto Backup
        autoBackupTitle: "Automatic Backup",
        autoBackupDesc: "Schedule automatic backups of your data.",
        autoBackupType: "Backup Type",
        autoBackupPassword: "Encryption Password (Optional)",
        autoBackupPasswordPlaceholder: "Leave empty for no encryption",
        backupEncryptionWarning: "Warning: If you lose this password, backups cannot be restored.",
        autoBackupLocation: "Backup Storage Path",
        backupRetentionCount: "Backups to keep",
    }
};

export const COUNTRY_TIMEZONE = {
    FR: "Europe/Paris",
    US: "America/New_York",
    ES: "Europe/Madrid",
    UK: "Europe/London",
    DE: "Europe/Berlin",
    RO: "Europe/Bucharest",
    TN: "Africa/Tunis",
    CH: "Europe/Zurich",
    TR: "Europe/Istanbul"
};

export const COUNTRY_NAMES = {
    FR: "France",
    US: "United States",
    ES: "Spain",
    UK: "United Kingdom",
    DE: "Germany",
    RO: "Romania",
    TN: "Tunisia",
    CH: "Switzerland",
    TR: "Turkey"
};

export const PERIOD_COLORS = {
    daily: "bg-blue-100 text-blue-800 dark:bg-blue-500 dark:text-white",
    weekly: "bg-purple-100 text-purple-800 dark:bg-purple-500 dark:text-white",
    monthly: "bg-amber-100 text-amber-800 dark:bg-amber-500 dark:text-white",
    yearly: "bg-rose-100 text-rose-800 dark:bg-rose-500 dark:text-white",
    hno: "bg-yellow-100 text-yellow-800 dark:bg-yellow-600 dark:text-white",
};

export function t(lang, key) {
    const L = I18N[lang] || I18N.EN;
    return L[key] ?? I18N.EN[key] ?? key;
}
