export const AuditAction = {
  // Authentication
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_MFA_ENABLED: 'AUTH_MFA_ENABLED',
  AUTH_MFA_DISABLED: 'AUTH_MFA_DISABLED',
  AUTH_PASSKEY_REGISTERED: 'AUTH_PASSKEY_REGISTERED',
  AUTH_PASSKEY_REMOVED: 'AUTH_PASSKEY_REMOVED',
  API_KEY_LIST: 'API_KEY_LIST',
  API_KEY_CREATE: 'API_KEY_CREATE',
  API_KEY_ROTATE: 'API_KEY_ROTATE',
  API_KEY_REVOKE: 'API_KEY_REVOKE',

  // User Management
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_RESTORED: 'USER_RESTORED',
  USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',

  // Group Management
  GROUP_CREATED: 'GROUP_CREATED',
  GROUP_UPDATED: 'GROUP_UPDATED',
  GROUP_DELETED: 'GROUP_DELETED',
  GROUP_MEMBER_ADDED: 'GROUP_MEMBER_ADDED',
  GROUP_MEMBER_REMOVED: 'GROUP_MEMBER_REMOVED',

  // Tasks
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  TASK_VALIDATED: 'TASK_VALIDATED',
  TASK_FAILED: 'TASK_FAILED',
  TASK_STATUS_UPDATED: 'TASK_STATUS_UPDATED',
  DELEGATION_CREATED: 'DELEGATION_CREATED',
  DELEGATION_UPDATED: 'DELEGATION_UPDATED',
  DELEGATION_REVOKED: 'DELEGATION_REVOKED',

  // System
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  SECURITY_POLICY_UPDATED: 'SECURITY_POLICY_UPDATED',

  // System Jobs
  SYSTEM_BACKUP_SUCCESS: 'SYSTEM_BACKUP_SUCCESS',
  SYSTEM_BACKUP_FAILURE: 'SYSTEM_BACKUP_FAILURE',
  SYSTEM_EXPORT_SUCCESS: 'SYSTEM_EXPORT_SUCCESS',
  SYSTEM_EXPORT_FAILURE: 'SYSTEM_EXPORT_FAILURE',
  SYSTEM_CLEANUP_SUCCESS: 'SYSTEM_CLEANUP_SUCCESS',
  SYSTEM_CLEANUP_FAILURE: 'SYSTEM_CLEANUP_FAILURE',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];

export enum AuditSeverity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum AuditCategory {
  AUTH = 'AUTH',
  USER = 'USER',
  GROUP = 'GROUP',
  TASK = 'TASK',
  SETTINGS = 'SETTINGS',
  SYSTEM = 'SYSTEM',
}
